/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.telainicial.usuario;

import javax.swing.JButton;
import javax.swing.JLabel;
import view.telainicial.ITelaInicial;

/**
 *
 * @author artur
 */
public class TelaInicialUsuario extends javax.swing.JFrame implements ITelaInicial {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicialUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        adicionarImagem = new javax.swing.JButton();
        PainelImagens = new javax.swing.JScrollPane();
        PainelImagensInterno = new javax.swing.JPanel();
        jLabelFoto1 = new javax.swing.JButton();
        jLabelFoto2 = new javax.swing.JButton();
        jLabelFoto3 = new javax.swing.JButton();
        jLabelFoto4 = new javax.swing.JButton();
        jLabelFoto5 = new javax.swing.JButton();
        jLabelFoto6 = new javax.swing.JButton();
        jLabelFoto7 = new javax.swing.JButton();
        jLabelFoto8 = new javax.swing.JButton();
        pedirPermissao = new javax.swing.JButton();
        removerImagem = new javax.swing.JButton();
        compartilhar = new javax.swing.JButton();
        notificacoes = new javax.swing.JButton();
        desfazer = new javax.swing.JButton();
        painelRodape = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelPermissao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionarImagem.setText("Adicionar Imagem");
        adicionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarImagemActionPerformed(evt);
            }
        });

        PainelImagensInterno.setLayout(new java.awt.GridLayout(4, 5, 2, 2));

        jLabelFoto1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto1.setBorder(null);
        jLabelFoto1.setBorderPainted(false);
        jLabelFoto1.setContentAreaFilled(false);
        jLabelFoto1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto1.setFocusTraversalPolicyProvider(true);
        jLabelFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelFoto1ActionPerformed(evt);
            }
        });
        PainelImagensInterno.add(jLabelFoto1);

        jLabelFoto2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto2.setBorder(null);
        jLabelFoto2.setBorderPainted(false);
        jLabelFoto2.setContentAreaFilled(false);
        jLabelFoto2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto2.setFocusTraversalPolicyProvider(true);
        PainelImagensInterno.add(jLabelFoto2);

        jLabelFoto3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto3.setBorder(null);
        jLabelFoto3.setBorderPainted(false);
        jLabelFoto3.setContentAreaFilled(false);
        jLabelFoto3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto3.setFocusTraversalPolicyProvider(true);
        jLabelFoto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelFoto3ActionPerformed(evt);
            }
        });
        PainelImagensInterno.add(jLabelFoto3);

        jLabelFoto4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto4.setBorder(null);
        jLabelFoto4.setBorderPainted(false);
        jLabelFoto4.setContentAreaFilled(false);
        jLabelFoto4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto4.setFocusTraversalPolicyProvider(true);
        PainelImagensInterno.add(jLabelFoto4);

        jLabelFoto5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto5.setBorder(null);
        jLabelFoto5.setBorderPainted(false);
        jLabelFoto5.setContentAreaFilled(false);
        jLabelFoto5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto5.setFocusTraversalPolicyProvider(true);
        PainelImagensInterno.add(jLabelFoto5);

        jLabelFoto6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto6.setBorder(null);
        jLabelFoto6.setBorderPainted(false);
        jLabelFoto6.setContentAreaFilled(false);
        jLabelFoto6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto6.setFocusTraversalPolicyProvider(true);
        jLabelFoto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelFoto6ActionPerformed(evt);
            }
        });
        PainelImagensInterno.add(jLabelFoto6);

        jLabelFoto7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto7.setBorder(null);
        jLabelFoto7.setBorderPainted(false);
        jLabelFoto7.setContentAreaFilled(false);
        jLabelFoto7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto7.setFocusTraversalPolicyProvider(true);
        PainelImagensInterno.add(jLabelFoto7);

        jLabelFoto8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFoto8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFoto8.setBorder(null);
        jLabelFoto8.setBorderPainted(false);
        jLabelFoto8.setContentAreaFilled(false);
        jLabelFoto8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFoto8.setFocusTraversalPolicyProvider(true);
        PainelImagensInterno.add(jLabelFoto8);

        PainelImagens.setViewportView(PainelImagensInterno);

        pedirPermissao.setText("Pedir Permissao");

        removerImagem.setText("Remover Imagem");
        removerImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerImagemActionPerformed(evt);
            }
        });

        compartilhar.setText("Compartilhar");

        notificacoes.setText("Notificações");

        desfazer.setText("Desfazer");

        labelNomeUsuario.setText("Nome: ");

        labelPermissao.setText("Permissão:");

        javax.swing.GroupLayout painelRodapeLayout = new javax.swing.GroupLayout(painelRodape);
        painelRodape.setLayout(painelRodapeLayout);
        painelRodapeLayout.setHorizontalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomeUsuario)
                .addGap(140, 140, 140)
                .addComponent(labelPermissao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRodapeLayout.setVerticalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeUsuario)
                    .addComponent(labelPermissao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(adicionarImagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PainelImagens, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pedirPermissao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(removerImagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(compartilhar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(notificacoes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(desfazer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(painelRodape, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelImagens)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removerImagem)
                    .addComponent(adicionarImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desfazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(compartilhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148)
                .addComponent(pedirPermissao)
                .addContainerGap())
            .addComponent(painelRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(PainelImagens, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(desfazer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adicionarImagem)
                                .addComponent(compartilhar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(removerImagem)
                                .addComponent(notificacoes))))
                    .addComponent(pedirPermissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(painelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerImagemActionPerformed

    }//GEN-LAST:event_removerImagemActionPerformed

    private void adicionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarImagemActionPerformed

    }//GEN-LAST:event_adicionarImagemActionPerformed

    private void jLabelFoto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelFoto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFoto3ActionPerformed

    private void jLabelFoto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelFoto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFoto6ActionPerformed

    private void jLabelFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelFoto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFoto1ActionPerformed

    @Override
    public JButton getBotaoAddImagem() {
        return adicionarImagem;
    }

    @Override
    public JButton getBotaoRemoverImagem() {
        return removerImagem;
    }

    @Override
    public JButton getBotaoCompartilhar() {
        return compartilhar;
    }

    @Override
    public JButton getBotaoNotificacoes() {
        return notificacoes;
    }

    public JButton getBotaoPedirPermissao() {
        return pedirPermissao;
    }

    @Override
    public JButton getjLabelFoto1() {
        return jLabelFoto1;
    }

    @Override
    public void setjLabelFoto1(JButton jLabelFoto1) {
        this.jLabelFoto1 = jLabelFoto1;
    }

    @Override
    public JButton getjLabelFoto2() {
        return jLabelFoto2;
    }

    @Override
    public void setjLabelFoto2(JButton jLabelFoto2) {
        this.jLabelFoto2 = jLabelFoto2;
    }

    @Override
    public JButton getjLabelFoto3() {
        return jLabelFoto3;
    }

    @Override
    public void setjLabelFoto3(JButton jLabelFoto3) {
        this.jLabelFoto3 = jLabelFoto3;
    }

    @Override
    public JButton getjLabelFoto4() {
        return jLabelFoto4;
    }

    @Override
    public void setjLabelFoto4(JButton jLabelFoto4) {
        this.jLabelFoto4 = jLabelFoto4;
    }

    @Override
    public JButton getjLabelFoto5() {
        return jLabelFoto5;
    }

    @Override
    public void setjLabelFoto5(JButton jLabelFoto5) {
        this.jLabelFoto5 = jLabelFoto5;
    }

    @Override
    public JButton getjLabelFoto6() {
        return jLabelFoto6;
    }

    @Override
    public void setjLabelFoto6(JButton jLabelFoto6) {
        this.jLabelFoto6 = jLabelFoto6;
    }

    @Override
    public JButton getjLabelFoto7() {
        return jLabelFoto7;
    }

    @Override
    public void setjLabelFoto7(JButton jLabelFoto7) {
        this.jLabelFoto7 = jLabelFoto7;
    }

    @Override
    public JButton getjLabelFoto8() {
        return jLabelFoto8;
    }

    @Override
    public void setjLabelFoto8(JButton jLabelFoto8) {
        this.jLabelFoto8 = jLabelFoto8;
    }

    @Override
    public JLabel getLabelNomeUsuario() {
        return labelNomeUsuario;
    }

    @Override
    public void setLabelNomeUsuario(JLabel labelNomeUsuario) {
        this.labelNomeUsuario = labelNomeUsuario;
    }

    @Override
    public JLabel getLabelPermissao() {
        return labelPermissao;
    }

    @Override
    public void setLabelPermissao(JLabel labelPermissao) {
        this.labelPermissao = labelPermissao;
    }

    @Override
    public JButton getBotaoDesfazer() {
        return desfazer;
    }

    @Override
    public void desligaTela() {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PainelImagens;
    private javax.swing.JPanel PainelImagensInterno;
    private javax.swing.JButton adicionarImagem;
    private javax.swing.JButton compartilhar;
    private javax.swing.JButton desfazer;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton jLabelFoto1;
    private javax.swing.JButton jLabelFoto2;
    private javax.swing.JButton jLabelFoto3;
    private javax.swing.JButton jLabelFoto4;
    private javax.swing.JButton jLabelFoto5;
    private javax.swing.JButton jLabelFoto6;
    private javax.swing.JButton jLabelFoto7;
    private javax.swing.JButton jLabelFoto8;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JLabel labelPermissao;
    private javax.swing.JButton notificacoes;
    private javax.swing.JPanel painelRodape;
    private javax.swing.JButton pedirPermissao;
    private javax.swing.JButton removerImagem;
    // End of variables declaration//GEN-END:variables

}
