/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.vernotificacoes;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author artur
 */
public class VerNotificacaoView extends javax.swing.JFrame {

    /**
     * Creates new form VerNotificacaoView
     */
    public VerNotificacaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotificacao = new javax.swing.JTable();
        apagarNotificações = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableNotificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableNotificacao);

        apagarNotificações.setText("Apagar Notificações");
        apagarNotificações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarNotificaçõesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(apagarNotificações)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apagarNotificações)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apagarNotificaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarNotificaçõesActionPerformed

    }//GEN-LAST:event_apagarNotificaçõesActionPerformed

    public JTable getTableNotificacao() {
        return tableNotificacao;
    }

    public void setTableNotificacao(JTable tableNotificacao) {
        this.tableNotificacao = tableNotificacao;
    }

    public int getLinhaTabela() {
        return tableNotificacao.getSelectedRow();
    }

    public int getColunaTabela() {
        return tableNotificacao.getSelectedColumn();
    }

    public JButton getApagarNotificações() {
        return apagarNotificações;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagarNotificações;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNotificacao;
    // End of variables declaration//GEN-END:variables
}
